apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dagster
  - ./cloudsql-proxy
  - ./redis
  - ./trino
  - ./consumer-trino
  #- ./metrics-service
  - ./nessie
  - ./nessie-cloudsql-proxy
  - ./sqlmesh-cloudsql-proxy
  - ./keda
  - ./mcp
  - ./agent
