apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/dagster
namespace: production-dagster
patches:
  - path: ./custom-helm-values.yaml
    target:
      type: HelmRelease
patchesStrategicMerge:
  - ./daemon-init-container.yaml
  - ./webserver-init-container.yaml
patchesJson6902:
  - target:
      kind: Namespace
      version: v1
      name: base-dagster
    patch: |-
      - op: replace
        path: /metadata/name
        value: production-dagster