apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: production-scheduler-query
spec:
  postRenderers:
    - kustomize:
        images:
          - name: ghcr.io/opensource-observer/oso
            newName: ghcr.io/opensource-observer/oso # {"$imagepolicy": "flux-system:oso:name"}
            newTag: deploy-20251222120147-577003d # {"$imagepolicy": "flux-system:oso:tag"}
  values:
    app:
      name: "oso-scheduler-query"
      args:
        - run
        - --directory
        - warehouse/scheduler
        - scheduler
        - run
        - query_run_requests
      serviceAccount:
        create: false
