[project]
name = "pyoso"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Icaro Guerra", email = "icaro@karibalabs.co" }
]
dependencies = []
